## Getting the data ready

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
X = heart_disease.drop("target", axis = 1)
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [5]:
y = heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [6]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [7]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [8]:
X.shape

(303, 13)

### Making sure it's all numerical

In [10]:
car_sales = pd.read_csv("car-sales-extended-missing-data.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [11]:
len(car_sales)

1000

In [12]:
# split into X/y
X= car_sales.drop("Price", axis = 1)
y = car_sales["Price"]

# split into training and test data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [13]:
# Build machine learning model
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'Nissan'

In [20]:
X.head()

     Make Colour  Odometer (KM)  Doors
0   Honda  White        35431.0    4.0
1     BMW   Blue       192714.0    5.0
2   Honda  White        84714.0    4.0
3  Toyota  White       154365.0    4.0
4  Nissan   Blue       181577.0    3.0

In [24]:
#Turn categories into numbersa
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)],
                               remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X;

In [26]:
pd.DataFrame(transformed_X).head()

                                                   0
0    (0, 1)\t1.0\n  (0, 9)\t1.0\n  (0, 12)\t1.0\n...
1    (0, 0)\t1.0\n  (0, 6)\t1.0\n  (0, 13)\t1.0\n...
2    (0, 1)\t1.0\n  (0, 9)\t1.0\n  (0, 12)\t1.0\n...
3    (0, 3)\t1.0\n  (0, 9)\t1.0\n  (0, 12)\t1.0\n...
4    (0, 2)\t1.0\n  (0, 6)\t1.0\n  (0, 11)\t1.0\n...

In [28]:
transformed_X_dense = transformed_X.toarray()
print(transformed_X_dense)

[[0.00000e+00 1.00000e+00 0.00000e+00 ... 0.00000e+00 0.00000e+00
  3.54310e+04]
 [1.00000e+00 0.00000e+00 0.00000e+00 ... 1.00000e+00 0.00000e+00
  1.92714e+05]
 [0.00000e+00 1.00000e+00 0.00000e+00 ... 0.00000e+00 0.00000e+00
  8.47140e+04]
 ...
 [0.00000e+00 0.00000e+00 1.00000e+00 ... 0.00000e+00 0.00000e+00
  6.66040e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 ... 0.00000e+00 0.00000e+00
  2.15883e+05]
 [0.00000e+00 0.00000e+00 0.00000e+00 ... 0.00000e+00 0.00000e+00
  2.48360e+05]]

In [30]:
pd.DataFrame(transformed_X_dense).head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,35431.0
1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,192714.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,84714.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,154365.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,181577.0

In [32]:
y_new = np.nan_to_num(y, nan =0)
y_new

array([15323., 19943., 28343., 13434., 14043., 23883.,  8473., 20306.,
        9374., 26683., 16259.,  6160., 16909., 11121., 18946., 16290.,
       34465., 17177.,  9109.,  6010., 24130., 29653., 22489., 21242.,
       14274., 15686., 13344., 10984.,  6135., 13586., 23929.,  6866.,
        9330.,  9780., 17516.,  8738., 23438., 15131.,  9224.,  6574.,
        9229.,  7100.,  6337., 19085.,  5743.,  5925., 25196., 16138.,
        6075.,  9928.,  7445., 13698., 17422.,  8269.,  9918., 48686.,
       15662., 19186., 11479., 12883., 24668., 12172., 25068., 20370.,
        5383., 18396.,  9648.,  6652.,  6386., 32379., 22436.,  6860.,
        5648., 12001., 18355., 20424., 15154., 18484.,  6502., 18310.,
        8200., 20142., 13199.,  5708., 13430., 10283.,  3300., 20936.,
       18160., 35988.,  5776., 18595.,  6481.,  6283.,  6762., 16337.,
       11392., 16519., 22296., 12196., 14202., 13250.,  7404.,  5316.,
       10125., 13614., 13283., 11584., 15617.,  4747.,  6391., 17802.,
       22943., 19502., 15541., 30407., 35432., 10091., 11485.,     0.,
       11192.,  3944., 19000.,  7994., 15604., 11648., 35600., 17596.,
       13427., 35358.,  7813.,  8743., 10628.,  4754.,  6784., 17584.,
       10582., 21754., 14795.,  8809., 19258., 34133., 20490., 31536.,
       30412., 14986., 23074.,  4566., 10038., 20497.,  8071., 10707.,
           0., 10835.,  5332., 19106., 12392., 20155., 10198.,  8260.,
       12402., 34110., 22616.,  6361., 14793., 15767.,  7861., 25847.,
        8693.,  7193., 21851.,     0., 20282.,  3247., 17980., 15960.,
           0., 34286., 10076., 23287., 12398., 20075., 12218., 20100.,
       13146., 14189.,  9290.,  7800., 13056., 39738.,  6848.,  7097.,
       13106.,  7846.,  8706.,  5454., 10316., 25133., 10596.,  6978.,
       25873., 13559., 26402., 10547., 16115., 12553., 12476., 18306.,
       33077., 22746.,  8856., 28013.,  9155.,  9530., 19892., 38128.,
       12531., 18198.,  5595., 12872., 29308., 12104., 19052., 25874.,
       23339., 21830., 22794., 35004.,  9734., 18691., 10823., 18346.,
        9953., 12086., 13208., 19936., 27787., 11092., 34856., 10456.,
        7725.,  7032., 15095., 16730., 14160.,  9521.,  5273., 10180.,
       39021.,     0., 14404., 16603.,  7076., 26954., 18182.,  5386.,
           0.,  8327.,     0., 12046., 13111., 35760., 29681., 10516.,
       32676.,  9675., 10374., 12146., 28414., 17917.,  9379., 27640.,
       48239., 22002., 15234., 13005., 28983., 17520., 17858., 10646.,
       16179., 16391., 17866.,  8566.,  5052., 17317.,  6431.,  9263.,
       13255., 11768.,  7708., 10602., 14089., 18524., 33353., 10872.,
       21921.,  7042.,  8460., 15184., 13200.,  8834., 10676., 12353.,
       23311., 18375., 10740.,  4863., 26846., 10380., 10888., 20237.,
       17556., 32887., 18058., 13560.,     0., 19357., 27057., 23868.,
        7813., 17035., 10429., 15088.,  6200., 11616.,  6029., 31392.,
       13652., 17860.,  3974., 24834.,  6460.,  7252., 11982.,     0.,
       10841.,     0., 13433., 24949., 20981., 17340.,  6962., 17036.,
       29635.,  4871., 25649.,  6672., 23719., 24938., 17597., 10439.,
       10301., 11738., 15623., 16223.,  7469.,  3974., 22176.,  5125.,
        9992.,  3893., 23902., 14502., 17876., 14198.,  8704., 14613.,
        6568.,  5008.,  7497., 13932., 15047.,  4753., 17284., 12434.,
       28993., 23017., 17961.,     0., 13492.,  7378.,  7061.,  5838.,
        6242., 13703., 14227., 22155., 26675.,  7598.,  8500., 14318.,
        3895., 10834., 16517., 19337., 11731., 12745.,     0., 35264.,
        8260., 15879., 10259., 30439., 13648., 23336.,  3594., 18327.,
       10855.,  8980.,  6121., 41294., 26677.,     0.,  5101., 16636.,
        8014.,  6241., 17127., 11411., 18180., 29293.,     0.,     0.,
        4946., 19720., 13508., 15652., 26926., 14312., 13310., 14074.,
        5260.,  8089., 16805.,  8753., 38060., 10030., 11076.,  9108.,
       15610., 13251., 28354., 23747., 19629.,  8380., 22989., 33324.,
       13147., 20642., 10344., 25490.,  7682., 12592.,  7827., 17622.,
       17171., 10101., 16319., 18653., 12201., 22597., 20893., 16892.,
       26973., 17256.,  6960., 21684.,  5094., 14931., 11773.,  5222.,
       10196., 16226.,     0., 28104., 16865., 26816.,  9545., 13647.,
           0., 14028., 31633., 12152., 16001., 18358.,  7443.,  4589.,
       17076., 21007., 29616., 22505., 25111.,  7376., 10919., 25763.,
        7882.,  4200., 29004.,  8979., 10450., 18029., 10278., 19175.,
           0., 24990., 21326.,     0., 17144., 12024., 20705., 29140.,
       23483., 13213., 16519.,  6357.,  8105., 10663., 12311.,     0.,
       19389., 13707., 13866.,  4941., 16366., 14086., 13560., 10597.,
       29089., 47260., 18919., 14442., 13244.,  6742., 22042., 35683.,
        4239., 20511.,     0., 19376., 10675., 13176., 17520.,  5653.,
       18919.,     0., 16072.,  9954., 33463., 40032., 22542.,  8687.,
        7982., 26078., 23280., 27744., 11135., 22825., 11648., 15508.,
       19036.,  6602., 14021., 10522., 18834., 20879., 29145., 17664.,
       13728., 19373.,  7903., 21236., 16220.,  7973.,  7802.,  6803.,
        8461., 10402.,  7994., 28655., 13127.,     0.,  5513., 20521.,
       45720., 13257.,  9529.,  7724., 30854., 12112., 10207., 33198.,
        5138., 27530., 14431., 30374., 22263.,  8137., 20590.,  8192.,
       20840., 11162., 26885.,  5157., 11749.,     0., 31206., 21953.,
       20450.,     0., 20622., 20242., 16774.,  8164., 25382.,  8916.,
       16320., 14524.,     0., 10580., 19408., 18142.,     0.,  8870.,
        7183., 10377., 13272., 22924., 17690., 17065., 28073., 29656.,
       23377., 10287., 14767., 16110., 28276., 21431., 25775.,  6884.,
       10494.,     0., 15372.,     0., 14204., 10024., 12392., 21451.,
       16273., 30320.,     0., 10061., 31208., 26834., 16867., 25735.,
       15260., 16308., 16719.,     0.,     0., 27888.,     0., 10241.,
           0., 15413.,  9402., 14717., 15154.,  8930., 11626., 28414.,
       18923.,  9649., 29401., 11364., 10352., 16908.,  3751.,  9919.,
       23728.,     0., 37518., 13263.,  9710., 32863., 12058.,  6690.,
        6504.,  4165., 16345.,  5843., 11210.,  6750., 15827., 16285.,
       17654., 13334., 27557., 19453.,  3509., 15297., 22587.,  9104.,
        6207., 29876., 12186., 15673., 17152., 36109., 18248., 20219.,
       15778.,  9685.,     0., 23844.,  6917., 28596., 11303., 22883.,
       50868., 27852., 26540., 12901., 14282.,  9222., 11298., 16464.,
       29363., 12950.,  7286.,  9500.,  6920., 18199., 10726.,  6956.,
       17609., 12650., 22949.,  4022., 19500., 21653., 18557., 23554.,
       14698., 20845., 16705., 20130., 13934.,  8513., 13722.,  7823.,
        5285., 30020., 23240., 11708., 17795.,  2796.,  8203.,  4968.,
       11854., 14432., 16645., 23064., 18222., 15962., 17258., 21679.,
        4358., 21612., 17635., 19271., 14590., 11233., 13637., 26308.,
       28830.,  8479.,  7157., 19545., 35687.,  4733.,  5865., 15967.,
       14944., 14331., 20108., 11036., 30323.,     0.,  8253.,  5135.,
       13608., 33040., 27868., 20503.,  4454., 13394.,  7910., 22643.,
        8690., 16488., 12609.,  8952.,  4566.,     0., 14084., 18640.,
       24629., 16879.,  9803., 45509., 23386., 32566., 30104., 15810.,
       10962., 12523.,  5933., 10747.,  5145.,  7217., 16016., 18440.,
       15097., 11140., 18429., 10821.,  9554., 10130.,     0., 29487.,
        9878., 17322.,     0., 30191., 20938., 36864.,  5905., 10349.,
       14026.,  5834., 13474., 24342., 12904.,  3125., 29638., 28599.,
       33817., 13417.,  7898., 16766., 32353.,  7350., 23945.,  8226.,
        6480., 18139.,     0.,  9450.,  5922., 22784., 12402.,  9074.,
       26813., 13650., 14145., 11733., 38984., 12988., 18962.,  5465.,
           0., 16652.,     0.,     0., 19832., 19838., 12408., 12362.,
        4606., 22921., 24494., 24242., 21580.,  6698., 19572., 27146.,
       25780., 10865., 22873., 27337., 14388.,  9785.,  6676., 11406.,
        9073., 22139., 16202., 14203.,  6214.,  7425., 38233., 21006.,
       19812., 23840., 52458.,  9362., 15861., 26940., 24122.,  6476.,
       12522.,  6567., 11182., 14588., 17315.,     0., 13519.,  9826.,
       23439.,  8321., 29959., 13546., 15666., 11454.,  5421.,  5594.,
       14134., 22816.,  7433., 14650., 24178., 35333., 12216.,  5548.,
        5168., 25104.,  7874., 17487.,     0.,  7955., 12641.,  8786.,
       24304., 17105., 17076.,     0., 24354., 16622., 11548., 14849.,
           0., 29551., 32509., 10261., 33758., 12315., 28422.,     0.,
       13070.,  4896., 15010.,  7126., 34231., 14691., 27598., 15224.,
           0., 35254., 16416., 24891., 17939.,  8430., 14345., 10429.,
        7435., 16835., 48419., 17940.,  6720.,  6446., 13273., 14671.,
        4196.,  9691., 26882.,  3825.,  8358., 13928.,  8082.,  9184.,
       27419.,  4696., 31666., 32042.,  5716., 31570.,  4001., 12732.])

In [34]:
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X_dense, y_new, test_size=0.2)

model.fit(X_train, y_train)

RandomForestRegressor()

In [36]:
model.score(X_test, y_test)

0.30285141503146695

# How to treat the missing values in a dataset
1. Fill them with some value (also known as imputing)
2. Remove the samples with missing data altogther

### Fill missing values using SciKit learn

In [38]:
car_sales_missing = pd.read_csv("car-sales-extended-missing-data.csv")
car_sales_missing.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [40]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [42]:
#Drop the rows with missing values
car_sales_missing.dropna(subset=["Price"], inplace = True)
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [58]:
# Split the data into X and y

X = car_sales_missing.drop("Price", axis = 1)
y = car_sales_missing["Price"]

np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

In [60]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

#fill the categorical values with "missing" and numerical values with mean
cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

#define columns

cat_features = ["Make", "Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

#create an imputer which fills the missing values
imputer = ColumnTransformer([
    ("cat_imputer", cat_imputer, cat_features),
    ("door_imputer", door_imputer, door_features),
    ("num_imputer", num_imputer, num_features),
                            ])

#transform the data

filled_X_train = imputer.fit_transform(X_train)
filled_X_test = imputer.transform(X_test)

filled_X_train

array([['Honda', 'White', 4.0, 71934.0],
       ['Toyota', 'Red', 4.0, 162665.0],
       ['Honda', 'White', 4.0, 42844.0],
       ...,
       ['Toyota', 'White', 4.0, 196225.0],
       ['Honda', 'Blue', 4.0, 133117.0],
       ['Honda', 'missing', 4.0, 150582.0]], dtype=object)

In [62]:
car_sales_filled_train = pd.DataFrame(filled_X_train, columns=["Make", "Colour", "Doors", "Odometer (KM)"])

car_sales_filled_test = pd.DataFrame(filled_X_test, columns=["Make", "Colour", "Doors", "Odometer (KM)"])
car_sales_filled.head()

     Make Colour Doors Odometer (KM)
0   Honda  White   4.0       35431.0
1     BMW   Blue   5.0      192714.0
2   Honda  White   4.0       84714.0
3  Toyota  White   4.0      154365.0
4  Nissan   Blue   3.0      181577.0

In [64]:
car_sales_filled.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [66]:
    # Import OneHotEncoder class from sklearn
    from sklearn.preprocessing import OneHotEncoder
    
    # Now let's one hot encode the features with the same code as before 
    categorical_features = ["Make", "Colour", "Doors"]
    one_hot = OneHotEncoder()
    transformer = ColumnTransformer([("one_hot", 
                                     one_hot, 
                                     categorical_features)],
                                     remainder="passthrough")
    
    # Fill train and test values separately
    transformed_X_train = transformer.fit_transform(car_sales_filled_train) # fit and transform the training data
    transformed_X_test = transformer.transform(car_sales_filled_test) # transform the test data
    
    # Check transformed and filled X_train
    transformed_X_train.toarray()

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 7.19340e+04],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.62665e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 4.28440e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.96225e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.33117e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.50582e+05]])

In [68]:
# Now we've transformed X, let's see if we can fit a model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor

# Setup model
model = RandomForestRegressor()

# Make sure to use transformed (filled and one-hot encoded X data)
model.fit(transformed_X_train, y_train)
model.score(transformed_X_test, y_test)

0.21229043336119102